
try {
    1 / 0
} catch err {
    print err
} finally {
    print 'finally'
}

